objects/AquaticSalesDirector__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Setting sale director name for AES approval process</description>
    <fields>
        <fullName>ID_of_Director__c</fullName>
        <label>Appover2</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Aquatic Sales Director</label>
</CustomObject>

objects/Facility__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aquatics_Examiner_Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aquatics Examiner Service</label>
        <referenceTo>Training_Events__c</referenceTo>
        <relationshipLabel>Facilities</relationshipLabel>
        <relationshipName>Facilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Address_1__c</fullName>
        <label>Facility Address 1</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Address_2__c</fullName>
        <label>Facility Address 2</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_City__c</fullName>
        <label>Facility City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_State__c</fullName>
        <label>Facility State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Zip__c</fullName>
        <label>Facility Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <label>Facility</label>
    <nameField>
        <label>Facility</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Training_Events__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Training Events</relationshipLabel>
        <relationshipName>Training_Event</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Facility_Address_1__c</fullName>
        <label>Facility Address 1</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Address_2__c</fullName>
        <label>Facility Address 2</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_City__c</fullName>
        <label>Facility City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_State__c</fullName>
        <label>Facility State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Facility_Zip__c</fullName>
        <label>Facility Zip</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Training Event</relationshipLabel>
        <relationshipName>Training_Event</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Training Event</label>
    <nameField>
        <displayFormat>TE-{000000}</displayFormat>
        <label>Training Events Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Event</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestupdateTrainingEventFacilityAddress.cls
@isTest
private class TestupdateTrainingEventFacilityAddress
{
    
    @isTest static void TestUpdatetrainingAddress()
    {
      String ADMIN_USER = 'System Administrator';
        
        List<Profile> adminProfile = [Select Id from Profile WHERE Name = :ADMIN_USER];        
        System.assertEquals( 1 , adminProfile .size() , 'These tests require an admin prfile Profile' );
        
        User u1 = new User(FirstName = 'tst_', LastName = 'user1',ProfileId = adminProfile[0].id, Email='standarduser1@testorg.com', 
                           EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US', LocaleSidKey='en_US',Alias ='als1', 
                           TimeZoneSidKey='America/Los_Angeles', UserName='standarduser1111@testorg.com');
        insert u1; 
        
        BGST_Profiles__c BGSTProf = new BGST_Profiles__c();
        BGSTProf.Name = 'Owner Profile';
        BGSTProf.Sales_User__c ='ARC BGST Sales User';
        BGSTProf.Sales_Admin__c ='ARC BGST Sales User';
        
        insert BGSTProf;
        
        /*List<AquaticSalesDirector__c> NewAq= new List<AquaticSalesDirector__c>();
        AquaticSalesDirector__c AquaticDir = new AquaticSalesDirector__c();
        AquaticDir.Name = 'ID of Director';
        AquaticDir.ID_of_Director__c ='005d0000000Tvtk';
        NewAq.add(AquaticDir);
        
        AquaticSalesDirector__c AquaticDir1 = new AquaticSalesDirector__c();
        AquaticDir1.Name = 'ID of Record';
        AquaticDir1.ID_of_Director__c ='0122F0000008y3a';
        NewAq.add(AquaticDir1);
        
        insert NewAq;*/

        system.runAs(u1)
        {
        Id rtId = Schema.SObjectType.Opportunity.RecordTypeInfosByName.get('AES').RecordTypeId;
        
        Account Acc=new Account();
        Acc.Name = 'Test Account';
        insert Acc;

        Opportunity opp=new opportunity();
        opp.Name = 'Test Opp';
        opp.AccountId = Acc.id;
        opp.CloseDate = System.today() + 5;
        opp.StageName = 'Approach'; 
        opp.RecordTypeId = rtId;
        insert opp;
                
        
        Test.startTest();
        List<Training_Events__c> TesttrainingEventUpdate = new List<Training_Events__c>();
        Training_Events__c TE1 = new Training_Events__c();
        TE1.Opportunity__c = opp.id;
        insert TE1;
        
        Facility__c Fac1=new Facility__c();
        Fac1.Name = 'Test Facility';
        Fac1.Facility_Address_1__c ='Test Address 1';
        Fac1.Facility_Address_2__c ='Test Address 2';
        Fac1.Facility_City__c = 'Test City';
        Fac1.Facility_State__c = 'AK';
        Fac1.Facility_Zip__c = '582145';
        Fac1.Account__c = Acc.id;
        Fac1.Aquatics_Examiner_Service__c = TE1.id;
        
        insert Fac1;
        Test.stopTest();
    
        }
    }
    
}