objects/Voucher__c.object
<CustomObject>
    <description>Store the Voucher required to enroll and register for a class</description>
    <fields>
        <fullName>ILT_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ILT Class</label>
        <referenceTo>redwing__ILT_Class__c</referenceTo>
        <relationshipLabel>Voucher</relationshipLabel>
        <relationshipName>Voucher</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QR_Code_Web_Address__c</fullName>
        <formula>/*IF(ILT_Class__c != null, IF(CONTAINS($Api.Partner_Server_URL_260, &apos;TransDev1&apos;), &apos;https://transdev1-americanredcross.cs52.force.com/learner/s/ClaimVoucher?voucherid=&apos; +  Id,
    (If (CONTAINS($Api.Partner_Server_URL_260, &apos;Partial&apos;), &apos;https://partial-americanredcross.cs78.force.com/learner/s/ClaimVoucher?voucherid=&apos; + Id,
    &apos;https://transuat-americanredcross.cs26.force.com/learner/s/ClaimVoucher?voucherid=&apos; +Id))), &apos;&apos;)*/
IF(ILT_Class__c != null, $Label.Learner_Community_URL + &apos;/s/ClaimVoucher?voucherid=&apos; + Id, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QR Code Web Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Voucher</description>
        <inlineHelpText>Current Status of Voucher</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Issued</fullName>
                    <default>true</default>
                    <label>Issued</label>
                </value>
                <value>
                    <fullName>Temp Hold</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Claimed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Voucher</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Voucher_Claim__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Voucher Claim Number to be used by Learner to access a Course</inlineHelpText>
        <label>Voucher Claim #</label>
        <type>Text</type>
    </fields>
    <label>Voucher</label>
    <nameField>
        <displayFormat>VN {000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PHSS_VoucherListController.cls
public class PHSS_VoucherListController {

    @AuraEnabled
    public static List<Voucher__c> getVoucherList(String recId) {
        List<Voucher__c> vouchList = [Select Id,Name,User__r.Name,Voucher_Claim__c,Status__c,ILT_Class__c,ILT_Class__r.Request_Type__c,User__c,QR_Code_Web_Address__c From Voucher__c 
                                      Where ILT_Class__c = :recId]; 
        return vouchList;
    }
}