objects/Voucher__c.object
<CustomObject>
    <description>Store the Voucher required to enroll and register for a class</description>
    <fields>
        <fullName>CC_Cart_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CC Cart Item related to the purchase of this voucher</description>
        <label>CC Cart Item</label>
        <referenceTo>ccrz__E_CartItem__c</referenceTo>
        <relationshipLabel>Voucher</relationshipLabel>
        <relationshipName>Voucher</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ILT_Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ILT Class</label>
        <referenceTo>redwing__ILT_Class__c</referenceTo>
        <relationshipLabel>Voucher</relationshipLabel>
        <relationshipName>Voucher</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Voucher</relationshipLabel>
        <relationshipName>Voucher</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RCO_Reservation_Timestamp__c</fullName>
        <description>Used in time-dependent workflow rule which releases reserved seat back to inventory after one hour from this time</description>
        <label>RCO Reservation Timestamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Voucher</description>
        <inlineHelpText>Current Status of Voucher</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Issued</fullName>
                    <default>true</default>
                    <label>Issued</label>
                </value>
                <value>
                    <fullName>Temp Hold</fullName>
                </value>
                <value>
                    <fullName>Reserved</fullName>
                </value>
                <value>
                    <fullName>Claimed</fullName>
                </value>
                <value>
                    <fullName>Blocked</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Pending Cancellation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Voucher</label>
    <nameField>
        <displayFormat>VN {000000}</displayFormat>
        <label>Voucher Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voucher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/phss_cc_VoucherUtil.cls
/**
 * Created by jbarker on 10/26/18.
 */

public with sharing class phss_cc_VoucherUtil {

    private static final String ISSUED_STATUS = 'Issued';
    private static final String TEMP_HOLD_STATUS = 'Temp Hold';
    private static final Integer RESERVATION_TIMESTAMP_OFFSET = -45;        // number of minutes to offset the reservation timestamp

    private static final String FAILED_TO_GET_REQUESTED_QUANTITY_OF_AVAILABLE_VOUCHERS = 'Failed to get the requested quantity of available vouchers.';
    private static final String FAILED_TO_MATCH_CART_ITEM_FOR_COURSE = 'Failed to match a cart item with a selected course.';
    private static final String FAILED_TO_MATCH_COURSE_FOR_CLASS = 'Failed to match course with selected class.';
    private static final String FAILED_TO_RESERVE_VOUCHERS = 'Failed to reserve vouchers.';


    /**
     * @description Requests vouchers for the specified ILT classes
     *
     * @param classQuantityMap
     *
     * @return
     */
    public static Map<String, List<Voucher__c>> requestVouchersForClasses(Map<String, Integer> classQuantityMap) {

        Map<String, List<Voucher__c>> voucherMap = new Map<String, List<Voucher__c>>();
        for (String classId : classQuantityMap.keySet()) {
            Integer quantity = classQuantityMap.get(classId);
            List<Voucher__c> vouchers = [
                    SELECT Id, ILT_Class__c, Status__c, CC_Cart_Item__c, Opportunity__c
                    FROM Voucher__c
                    WHERE ILT_Class__c = :classId
                    AND Status__c = :ISSUED_STATUS
                    LIMIT :quantity
                    FOR UPDATE
            ];
            if (vouchers.size() == quantity) {
                voucherMap.put(classId, vouchers);
            }
            else {
                throw new phss_cc_Exception(FAILED_TO_GET_REQUESTED_QUANTITY_OF_AVAILABLE_VOUCHERS);
            }
        }

        return voucherMap;
    }

    /**
     * @description Reserves vouchers for the specified ILT classes
     *
     * @param classVoucherMap
     * @param cartData
     */
    public static List<Voucher__c> reserveVouchersForCartItems(Map<String, List<Voucher__c>> classVoucherMap, Map<String, String> classCourseMap, Map<String, String> courseCartItemMap, String opportunityId) {

        List<Voucher__c> allVouchers = new List<Voucher__c>();
        if (classVoucherMap.keySet().size() > 0) {

            System.Savepoint sp =  Database.setSavepoint();

            try {
                for (String classId : classVoucherMap.keySet()) {
                    List<Voucher__c> vouchers = classVoucherMap.get(classId);
                    String courseId = classCourseMap.get(classId);
                    if (courseId == null) {
                        throw new phss_cc_Exception(FAILED_TO_MATCH_COURSE_FOR_CLASS);
                    }

                    String cartItemId = courseCartItemMap.get(courseId);
                    if (cartItemId == null) {
                        throw new phss_cc_Exception(FAILED_TO_MATCH_CART_ITEM_FOR_COURSE);
                    }

                    for (Voucher__c voucher : vouchers) {
                        voucher.Opportunity__c = opportunityId;
                        voucher.Status__c = TEMP_HOLD_STATUS;
                        voucher.RCO_Reservation_Timestamp__c = getReservationDatetime();
                        voucher.CC_Cart_Item__c = cartItemId;
                    }

                    allVouchers.addAll(vouchers);
                }

                update allVouchers;

            } catch (Exception e) {
                Database.rollback(sp);
                throw new phss_cc_Exception(FAILED_TO_RESERVE_VOUCHERS, e);
            }
        }

        return allVouchers;
    }

    /**
     * @description Gets the reservation Datetime
     *
     * @return
     */
    private static Datetime getReservationDatetime() {
        return Datetime.now().addMinutes(RESERVATION_TIMESTAMP_OFFSET);
    }
}